### PR TITLE
Date fromString

### PR DESCRIPTION
**Pull request by darkerbit**
It is pretty much semi-complete for now, later updates to datesaurus will improve it probably

### CODE REVIEW

**Comment by zephyrtronium** [comment]
Thank you for working on this! Before I accept the pull request, I'd like the backing library to support the same directives as https://godoc.org/gitlab.com/variadico/lctime (at least as far as simple replacements can get), and the go.mod entry updated to require that version.

**Comment by darkerbit** [comment]
I am currently working on adding such support to the backing library.

**Comment by darkerbit** [comment]
It now uses lctime itself to create the format string but for some reason lctime isn't formatting the years correctly. Some debugging necessary.

**Comment by darkerbit** [comment]
Nevermind, turns out pushing it fixed it in some magical way. Date fromString is now completely done.

**Pull request merged**
